### ISSUE TITLE
unsup/sub: move to utl/sub?

### ISSUE THREAD

**Issue by dennisguse** [openitu/STL#97] opened 2018-10-11 21:21 UTC
`unsup/sub` is used to compare test results.
However, at the moment this program is in the "unsupported" folder.

If it is used by the STL in future, we should make it supported.

What about moving it to `utl`?

**Comment by dennisguse** [comment] 2018-10-14 16:49
And one more question: should we rename `sub`?
I mean the name is not really self explaining.
What about `substract` or `signal-diff`?

**Comment by othiman** [comment] 2018-10-17 08:53
I think moving to utl would be a great idea. I also like `signal-diff` as name. Anyhow, I propose to make the move and rename after merging @ludomal  and my PRs since otherwise there would be merge conflicts with the recent versions of the PRs.

**Comment by ludomal** [comment] 2018-10-17 17:36
I have moved sub-add.c to utl/signal-diff.c (See PR #103).
I am happy to merge now or later. The regression scripts will have to be updated anyway.

**Comment by dennisguse** [comment] 2018-10-17 19:19
I would prefer merging #103 first.
Otherwise, we would add one commit fixing the test and then another fixing the refactoring.

@ludomal Awesome :)

**Closed** 2018-10-17 20:03 UTC
